### ISSUE TITLE
Add cookbook to supermarket

### ISSUE THREAD

**Issue by poliva83** [chef-cookbooks/chef-server-cluster#36]
Was trying to get my wrapper cookbook to depend on this cookbook and noticed its not on Supermarket.

**Comment by jtimberman** [comment]
This cookbook is purposely not shared on supermarket.

**Comment by poliva83** [comment]
That is fine. Is the reason being because cookbook is still in flux state?

**Comment by jtimberman** [comment]
Two reasons:

1. Yes, it's in a state of flux, and development. We have some internal projects that are targeted at making the over all experience of installing clusters of our software easier.
2. The original intent was focused around using this for Hosted Chef. It's an open source project, but it's not a "community cookbook."

The scope of original intent is changed, partly due to the first reason. Also because we found that providing a library cookbook of solid primitives, like the [chef-ingredient](https://supermarket.chef.io/cookbooks/chef-ingredient) cookbook is a much better overall solution for a "community" cookbook.

Does that make sense?

**Comment by poliva83** [comment]
Yes that makes scene. So are these other internal projects will be focused more on HA topology clusters?

I was trying to wrap this cookbook slightly to experiment with bringing up a cluster using chef provisioning and chef-zero workflow and was able to get quite a lot farther then when I tried this in Feb/March. Probably do to the re-factoring done from chef-server-ingredient to chef-ingredient.
